### ISSUE TITLE
Deployment on Dedicated Nodes

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/test_feedback#102]
Tested on devnet

Trying to deploy on any of the nodes available on the dedicated nodes tab in the [portal](https://portal.dev.grid.tf/) without reserving a node gives an error as it is supposed to but the error is not clear or user friendly
```
Error: Failed to create contract on node: 21 due to Failed to apply createNodeContract in module smartContractModule with 21,,fcc667bbad59c37d2eb093e63fceed80,0 due to error: undefined
```
![image](https://user-images.githubusercontent.com/101194226/164200810-76ce3c86-7c52-4b53-a818-ad6466a3fd2f.png)

Suggestion: Dedicated nodes should not be available in the capacity filter for deployment once they are reserved or marked as dedicated nodes and available for reservation or they could be available in the capacity filter but marked as reserved/dedicated node.

**Comment by mohamedamer453** [comment]
Same issue when deploying from terraform the issue is unclear and the error message is not user friendly at all.

```
grid_network.net1: Creating...
grid_network.net1: Still creating... [10s elapsed]
╷
│ Error: Plugin did not respond
│ 
│   with grid_network.net1,
│   on main.tf line 12, in resource "grid_network" "net1":
│   12: resource "grid_network" "net1" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The
│ plugin logs may contain more details.
╵

Stack trace from the terraform-provider-grid_v0.1.27 plugin:

panic: runtime error: index out of range [24] with length 16

goroutine 97 [running]:
github.com/threefoldtech/substrate-client.(*Substrate).checkForError(0xc00000d2f0, 0xc0002cbc80, 0x2c, {0xff, 0x3a, 0xd0, 0x77, 0xc1, 0xd9, 0x64, ...}, ...)
        github.com/threefoldtech/substrate-client@v0.0.0-20220328075445-99d0ff259160/utils.go:237 +0x3dd
github.com/threefoldtech/substrate-client.(*Substrate).CreateNodeContract(0xc0005082d0, {0xf885d0, 0xc000122700}, 0x0, {0x0, 0x0, 0x0}, {0xc0005be320, 0x20}, 0x0)
        github.com/threefoldtech/substrate-client@v0.0.0-20220328075445-99d0ff259160/contract.go:184 +0x2c7
github.com/threefoldtech/terraform-provider-grid/internal/provider.deployConsistentDeployments({0xf7c3e8, 0xc00049ff20}, 0xc000468460, 0xf82200, 0xc0002e61a0, {0xf66ca0, 0xc0005084f8}, 0xc000296180)
        github.com/threefoldtech/terraform-provider-grid/internal/provider/common.go:402 +0x7eb
github.com/threefoldtech/terraform-provider-grid/internal/provider.deployDeployments({0xf7c3e8, 0xc00049ff20}, 0x0, 0x0, 0xf66ca0, {0xf66ca0, 0xc0005084f8}, 0xc000296180, 0x1)
        github.com/threefoldtech/terraform-provider-grid/internal/provider/common.go:334 +0x10b
github.com/threefoldtech/terraform-provider-grid/internal/provider.(*NetworkDeployer).Deploy(0xc0002d34b8, {0xf7c3e8, 0xc00049ff20}, 0xd)
        github.com/threefoldtech/terraform-provider-grid/internal/provider/resource_network.go:638 +0xb9
github.com/threefoldtech/terraform-provider-grid/internal/provider.resourceNetworkCreate({0xf7c3e8, 0xc00049ff20}, 0xc00022f6c0, {0xcbd040, 0xc000296180})
        github.com/threefoldtech/terraform-provider-grid/internal/provider/resource_network.go:681 +0x4f0
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc0002130a0, {0xf7c378, 0xc000123a80}, 0x2, {0xcbd040, 0xc000296180})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/resource.go:341 +0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0002130a0, {0xf7c378, 0xc000123a80}, 0xc0004a9ba0, 0xc0001d7180, {0xcbd040, 0xc000296180})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/resource.go:467 +0x871
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc00000d308, {0xf7c378, 0xc000123a80}, 0xc0002c1a40)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/grpc_provider.go:977 +0xd8a
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc0001aae00, {0xf7c420, 0xc0005e7a10}, 0xc0004bb9d0)
        github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/tf5server/server.go:603 +0x30e
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0xe023a0, 0xc0001aae00}, {0xf7c420, 0xc0005e7a10}, 0xc00049f440, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001fea80, {0xf8b9d0, 0xc000410000}, 0xc0000b0ea0, 0xc0003e2f60, 0x15c9ac0, 0x0)
        google.golang.org/grpc@v1.41.0/server.go:1279 +0xccf
google.golang.org/grpc.(*Server).handleStream(0xc0001fea80, {0xf8b9d0, 0xc000410000}, 0xc0000b0ea0, 0x0)
        google.golang.org/grpc@v1.41.0/server.go:1608 +0xa2a
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.41.0/server.go:923 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.41.0/server.go:921 +0x294

Error: The terraform-provider-grid_v0.1.27 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

**Comment by mohamedamer453** [comment]
same issue with tsclient

```
Rolling back deployments
/home/mohamed/Desktop/Github/tsclient2/grid3_client_ts/src/high_level/twinDeploymentHandler.ts:388
            throw Error(e);
                  ^
Error: Error: Failed to create contract on node: 22 due to Failed to apply createNodeContract in module smartContractModule with 22,,720f7455c4c6aba21d415e8badea0f7e,0 due to error: undefined
    at TwinDeploymentHandler.handle (/home/mohamed/Desktop/Github/tsclient2/grid3_client_ts/src/high_level/twinDeploymentHandler.ts:388:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async MachinesModule.deploy (/home/mohamed/Desktop/Github/tsclient2/grid3_client_ts/src/modules/machines.ts:76:27)
    at async MachinesModule.descriptor.value (/home/mohamed/Desktop/Github/tsclient2/grid3_client_ts/src/modules/utils.ts:14:16)
    at async MachinesModule.descriptor.value (/home/mohamed/Desktop/Github/tsclient2/grid3_client_ts/src/helpers/validator.ts:23:16)
    at async main (/home/mohamed/Desktop/Github/tsclient2/grid3_client_ts/scripts/single_vm.ts:45:17)
```
