### ISSUE TITLE
TC335 - Can add & remove node to kubernetes cluster from ts client

### ISSUE THREAD

**Issue by dmitri-alleo** [threefoldtech/test_feedback#153]
Generally, deployment of anything with TS client results into the following error:

```
sw-alleo:grid3_client_ts (1d5efba2*) $ yarn run ts-node --project tsconfig-node.json scripts/kubernetes.ts 
yarn run v1.22.18
$ /home/sw/AlleoTech/001_Projects/002_Clients/TFGrid/grid2/grid3_client_ts/node_modules/.bin/ts-node --project tsconfig-node.json scripts/kubernetes.ts
/home/sw/AlleoTech/001_Projects/002_Clients/TFGrid/grid2/grid3_client_ts/node_modules/ts-node/src/index.ts:944
          throw new TypeError(`${relative(cwd, fileName)}: Emit skipped`);
                ^
TypeError: src/index.js: Emit skipped
    at getOutput (/home/sw/AlleoTech/001_Projects/002_Clients/TFGrid/grid2/grid3_client_ts/node_modules/ts-node/src/index.ts:944:17)
    at Object.compile (/home/sw/AlleoTech/001_Projects/002_Clients/TFGrid/grid2/grid3_client_ts/node_modules/ts-node/src/index.ts:1243:30)
    at Module.m._compile (/home/sw/AlleoTech/001_Projects/002_Clients/TFGrid/grid2/grid3_client_ts/node_modules/ts-node/src/index.ts:1370:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Object.require.extensions.<computed> [as .js] (/home/sw/AlleoTech/001_Projects/002_Clients/TFGrid/grid2/grid3_client_ts/node_modules/ts-node/src/index.ts:1374:12)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/sw/AlleoTech/001_Projects/002_Clients/TFGrid/grid2/grid3_client_ts/scripts/kubernetes.ts:1:1)
error Command failed with exit code 1.
```

Env: Testnet
TS Grid client version: 1.3.1

**Comment by dmitri-alleo** [comment]
The tolls version installed locally:

```
sw-alleo:grid3_client_ts (1d5efba2*) $ yarn -v                                                            
1.22.18
sw-alleo:grid3_client_ts (1d5efba2*) $ npm -v        
8.6.0
sw-alleo:grid3_client_ts (1d5efba2*) $ node -v
v16.13.1
```

**Comment by xmonader** [comment]
@AhmedHanafy725 please give it a look
