### ISSUE TITLE
TC593 -  Verify Deployment after Unreserving a node (TsClient)

### ISSUE THREAD

**Issue by dmitri-alleo** [threefoldtech/test_feedback#158]
Env: Testnet 
Grid3 Version: 1.3.1

Fails with:
```
sw-alleo:grid3_client_ts (1d5efba2*) $ yarn run ts-node --project tsconfig-node.json scripts/single_vm.ts 
yarn run v1.22.18
$ /home/sw/AlleoTech/001_Projects/002_Clients/TFGrid/grid2/grid3_client_ts/node_modules/.bin/ts-node --project tsconfig-node.json scripts/single_vm.ts
/home/sw/AlleoTech/001_Projects/002_Clients/TFGrid/grid2/grid3_client_ts/node_modules/ts-node/src/index.ts:944
          throw new TypeError(`${relative(cwd, fileName)}: Emit skipped`);
                ^
TypeError: src/index.js: Emit skipped
    at getOutput (/home/sw/AlleoTech/001_Projects/002_Clients/TFGrid/grid2/grid3_client_ts/node_modules/ts-node/src/index.ts:944:17)
    at Object.compile (/home/sw/AlleoTech/001_Projects/002_Clients/TFGrid/grid2/grid3_client_ts/node_modules/ts-node/src/index.ts:1243:30)
    at Module.m._compile (/home/sw/AlleoTech/001_Projects/002_Clients/TFGrid/grid2/grid3_client_ts/node_modules/ts-node/src/index.ts:1370:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Object.require.extensions.<computed> [as .js] (/home/sw/AlleoTech/001_Projects/002_Clients/TFGrid/grid2/grid3_client_ts/node_modules/ts-node/src/index.ts:1374:12)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/sw/AlleoTech/001_Projects/002_Clients/TFGrid/grid2/grid3_client_ts/scripts/single_vm.ts:1:1)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by xmonader** [comment]
Hi @dmitri-alleo , I'll be considering your issues reported for the tsclient as false and will close them, because they're not really issues

![image](https://user-images.githubusercontent.com/64129/169949597-9cfc9ad5-e179-43d1-9576-d5a55bca50d5.png)
https://github.com/threefoldtech/grid3_client_ts/actions
