### ISSUE TITLE
TS Client documentation is either outdated or has broken instructions

### ISSUE THREAD

**Issue by dmitri-alleo** [threefoldtech/test_feedback#174]
When following the documentation on how to set the TS client up, doesn't allow to set the TS client properly,

https://library.threefold.me/info/manual/#/manual3_iac/grid3_javascript/manual__grid3_javascript_installation

once following all of the instruction and trying to run the scripts to provision any of the resource getting the same error

```
sw-alleo:grid3_client_ts (1d5efba2*) $ yarn run ts-node --project tsconfig-node.json scripts/single_vm.ts 
yarn run v1.22.18
$ /home/sw/AlleoTech/001_Projects/002_Clients/TFGrid/grid2/grid3_client_ts/node_modules/.bin/ts-node --project tsconfig-node.json scripts/single_vm.ts
/home/sw/AlleoTech/001_Projects/002_Clients/TFGrid/grid2/grid3_client_ts/node_modules/ts-node/src/index.ts:944
          throw new TypeError(`${relative(cwd, fileName)}: Emit skipped`);
                ^
TypeError: src/index.js: Emit skipped
    at getOutput (/home/sw/AlleoTech/001_Projects/002_Clients/TFGrid/grid2/grid3_client_ts/node_modules/ts-node/src/index.ts:944:17)
    at Object.compile (/home/sw/AlleoTech/001_Projects/002_Clients/TFGrid/grid2/grid3_client_ts/node_modules/ts-node/src/index.ts:1243:30)
    at Module.m._compile (/home/sw/AlleoTech/001_Projects/002_Clients/TFGrid/grid2/grid3_client_ts/node_modules/ts-node/src/index.ts:1370:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Object.require.extensions.<computed> [as .js] (/home/sw/AlleoTech/001_Projects/002_Clients/TFGrid/grid2/grid3_client_ts/node_modules/ts-node/src/index.ts:1374:12)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/sw/AlleoTech/001_Projects/002_Clients/TFGrid/grid2/grid3_client_ts/scripts/single_vm.ts:1:1)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

Env: Testnet
Grid3 Version: 1.3.1

**Comment by AhmedHanafy725** [comment]
In a new container with image `ubuntu:20.04`
- install nodejs
- clone the repo 
- npm install in the repo's root
- update scripts/config.json
- run any script

and all worked fine 
@dmitri-alleo  can you try this and comment on the issue if it didn't work?

**Comment by dmitri-alleo** [comment]
@AhmedHanafy725 thank you, will give it a try and will let you know

**Comment by dmitri-alleo** [comment]
@AhmedHanafy725 trying to run the script from the Ubuntu 20.04 container, getting this response:

```
root@5d554bcc98e6:~/grid3_client_ts# yarn run ts-node scripts/single_vm.ts
yarn run v1.22.18
$ /root/grid3_client_ts/node_modules/.bin/ts-node scripts/single_vm.ts
/root/grid3_client_ts/node_modules/ts-node/src/index.ts:750
    return new TSError(diagnosticText, diagnosticCodes);
           ^
TSError: ⨯ Unable to compile TypeScript:
scripts/single_vm.ts:2:10 - error TS7034: Variable 'config' implicitly has type 'any' in some locations where its type cannot be determined.

2 import { config, getClient } from "./client_loader";
           ~~~~~~
scripts/single_vm.ts:29:14 - error TS7005: Variable 'config' implicitly has an 'any' type.

29     SSH_KEY: config.ssh_key,
                ~~~~~~

    at createTSError (/root/grid3_client_ts/node_modules/ts-node/src/index.ts:750:12)
    at reportTSError (/root/grid3_client_ts/node_modules/ts-node/src/index.ts:754:19)
    at getOutput (/root/grid3_client_ts/node_modules/ts-node/src/index.ts:941:36)
    at Object.compile (/root/grid3_client_ts/node_modules/ts-node/src/index.ts:1243:30)
    at Module.m._compile (/root/grid3_client_ts/node_modules/ts-node/src/index.ts:1370:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Object.require.extensions.<computed> [as .ts] (/root/grid3_client_ts/node_modules/ts-node/src/index.ts:1374:12)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12) {
  diagnosticText: "\x1B[96mscripts/single_vm.ts\x1B[0m:\x1B[93m2\x1B[0m:\x1B[93m10\x1B[0m - \x1B[91merror\x1B[0m\x1B[90m TS7034: \x1B[0mVariable 'config' implicitly has type 'any' in some locations where its type cannot be determined.\n" +
    '\n' +
    '\x1B[7m2\x1B[0m import { config, getClient } from "./client_loader";\n' +
    '\x1B[7m \x1B[0m \x1B[91m         ~~~~~~\x1B[0m\n' +
    "\x1B[96mscripts/single_vm.ts\x1B[0m:\x1B[93m29\x1B[0m:\x1B[93m14\x1B[0m - \x1B[91merror\x1B[0m\x1B[90m TS7005: \x1B[0mVariable 'config' implicitly has an 'any' type.\n" +
    '\n' +
    '\x1B[7m29\x1B[0m     SSH_KEY: config.ssh_key,\n' +
    '\x1B[7m  \x1B[0m \x1B[91m             ~~~~~~\x1B[0m\n',
  diagnosticCodes: [ 7034, 7005 ]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

The details of the setup
```
root@5d554bcc98e6:~/grid3_client_ts# git branch
* (HEAD detached at 1.3.1)
  development
root@5d554bcc98e6:~/grid3_client_ts# node -v
v16.15.0
root@5d554bcc98e6:~/grid3_client_ts# npm -v
8.5.5
root@5d554bcc98e6:~/grid3_client_ts# tsc -v
Version 4.6.4
root@5d554bcc98e6:~/grid3_client_ts# yarn -v
1.22.18
```

The configuration
```
root@5d554bcc98e6:~/grid3_client_ts# cat scripts/config.json 
{
       "network": "test",
       "mnemonic": "<mnemonic_from_the_account>",
       "rmb_proxy": true,
       "storeSecret": "secret",
       "ssh_key": "<public_SSH_key>"
}

root@5d554bcc98e6:~/grid3_client_ts# cat src/server/config.json 
{
    "network": "test",
    "mnemonic": "<mnemonic>",
    "rmb_proxy": false,
    "storeSecret": "secret",
    "keypairType": "sr25519"
}

```

**Comment by AhmedHanafy725** [comment]
@dmitri-alleo the project configuration is not passed while running the script, can you try the following cmd?
```bash 
yarn ts-node --project ./tsconfig-node.json scripts/single_vm.ts  
```

**Comment by dmitri-alleo** [comment]
@AhmedHanafy725 getting a different error now

```
yarn run v1.22.18
$ /root/grid3_client_ts/node_modules/.bin/ts-node --project ./tsconfig-node.json scripts/single_vm.ts
/root/grid3_client_ts/node_modules/ts-node/src/index.ts:944
          throw new TypeError(`${relative(cwd, fileName)}: Emit skipped`);
                ^
TypeError: src/index.js: Emit skipped
    at getOutput (/root/grid3_client_ts/node_modules/ts-node/src/index.ts:944:17)
    at Object.compile (/root/grid3_client_ts/node_modules/ts-node/src/index.ts:1243:30)
    at Module.m._compile (/root/grid3_client_ts/node_modules/ts-node/src/index.ts:1370:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Object.require.extensions.<computed> [as .js] (/root/grid3_client_ts/node_modules/ts-node/src/index.ts:1374:12)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/root/grid3_client_ts/scripts/single_vm.ts:1:1)
error Command failed with exit code 1.
```

**Comment by mohamedamer453** [comment]
> In a new container with image `ubuntu:20.04`
> 
> * install nodejs
> * clone the repo
> * npm install in the repo's root
> * update scripts/config.json
> * run any script
> 
> and all worked fine @dmitri-alleo can you try this and comment on the issue if it didn't work?


I followed the exact steps mentioned here and on the [grid3_client_ts](https://github.com/threefoldtech/grid3_client_ts#grid3_client_ts) and i was able to run it successfully from an Ubuntu 20.04 container. 

The exact steps i followed:

- I deployed a VM through the weblets.
- in the vm i installed the prerequisites mentioned in the docs:
    - node 16.13.1 or higher
    - npm 8.2.0 or higher
    - may need to install libtool `apt-get install libtool`
- Then i installed git and cloned the grid3_client_ts repo.
- after cloning i navigated to the repo and executed `npm install`
- After `npm install` finished i updated the `scripts/config.json` with my network, Mnemionics and ssh_key.
- Then i executed this command ` npx ts-node --project tsconfig-node.json scripts/single_vm.ts ` to run the `single_vm.ts` script

and i was able to successfully deploy a VM
```
root@testTsClient:~/grid3_client_ts# npx ts-node --project tsconfig-node.json scripts/single_vm.ts
Credentials not all found in env variables. Loading all credentials from default config.json...
Key with address: 5CUKN1tAqUFhzgbcYUPqCcLeEPdJDBiF6i6s5GMqyRVeFEpZ is loaded.
Executing method: getTwinIdByAccountId with args: 5CUKN1tAqUFhzgbcYUPqCcLeEPdJDBiF6i6s5GMqyRVeFEpZ
Validation succeed
Executing method: getBalanceOf with args: 5CUKN1tAqUFhzgbcYUPqCcLeEPdJDBiF6i6s5GMqyRVeFEpZ
Adding node 17 to network wedtest
Sending {try 1}: https://gridproxy.dev.grid.tf/twin/25
Sending {try 1}: Success
{ retqueue: 'b6f3f61d-646f-417e-9b81-e9c31038eb59' }
Reading: https://gridproxy.dev.grid.tf/twin/25/b6f3f61d-646f-417e-9b81-e9c31038eb59
Node 17 reserved ports: [8082,5070,80,443,6913,9943,9944,9945]
Generating peers for network wedtest
Creating a vm on node: 17, network: wedtest with private ip: 10.249.2.2
Merging workloads
Validation succeed
Updating network workload with name: wedtest
Deploying on node_id: 17
Lock acquired
phase: {"applyExtrinsic":1}, section: smartContractModule, method: ContractCreated
phase: {"applyExtrinsic":1}, section: system, method: ExtrinsicSuccess
Lock released
Contract with id: 2670 has been created
Sending {try 1}: https://gridproxy.dev.grid.tf/twin/25
Sending {try 1}: Success
{ retqueue: 'ada8495e-bd7d-4e25-a8e2-94013b4cbf0a' }
Reading: https://gridproxy.dev.grid.tf/twin/25/ada8495e-bd7d-4e25-a8e2-94013b4cbf0a
Couldn't get the response
Reading: https://gridproxy.dev.grid.tf/twin/25/ada8495e-bd7d-4e25-a8e2-94013b4cbf0a
A deployment has been created on node_id: 17 with contract_id: 2670
Waiting for deployment with contract_id: 2670 to be ready
Executing method: getContractByID with args: 2670
Sending {try 1}: https://gridproxy.dev.grid.tf/twin/25
Sending {try 1}: Success
{ retqueue: '367b5306-45f6-46dc-b953-3d97eee59971' }
Reading: https://gridproxy.dev.grid.tf/twin/25/367b5306-45f6-46dc-b953-3d97eee59971
Sending {try 1}: https://gridproxy.dev.grid.tf/twin/25
Sending {try 1}: Success
{ retqueue: '9c3b0b9e-f517-4739-aefb-845fe19f1374' }
Reading: https://gridproxy.dev.grid.tf/twin/25/9c3b0b9e-f517-4739-aefb-845fe19f1374
Sending {try 1}: https://gridproxy.dev.grid.tf/twin/25
Sending {try 1}: Success
{ retqueue: '887df229-a56c-4277-a9af-422f8dfb2349' }
Reading: https://gridproxy.dev.grid.tf/twin/25/887df229-a56c-4277-a9af-422f8dfb2349
{
  contracts: {
    created: [
      {
        version: 3,
        state: { created: null },
        contract_id: 2670,
        twin_id: 60,
        contract_type: {
          nodeContract: {
            node_id: 17,
            deployment_data: '0x7b2774657374564d73273a20747275657d',
            deployment_hash: '0x3034303534333830666666306663383639323934366261663337626336376134',
            public_ips: 0,
            public_ips_list: []
          }
        }
      }
    ],
    updated: [],
    deleted: []
  },
  wireguard_config: ''
}
Executing method: getContractByID with args: 2670
Sending {try 1}: https://gridproxy.dev.grid.tf/twin/25
Sending {try 1}: Success
{ retqueue: '4d5d9d95-d111-4a91-80fd-ad0a7ef2d121' }
Reading: https://gridproxy.dev.grid.tf/twin/25/4d5d9d95-d111-4a91-80fd-ad0a7ef2d121
[
  {
    version: 0,
    contractId: 2670,
    nodeId: 17,
    name: 'testvm',
    created: 1653467160,
    status: 'ok',
    message: '',
    flist: 'https://hub.grid.tf/tf-official-apps/base:latest.flist',
    publicIP: null,
    planetary: '300:487a:7ea1:5b4e:ec6e:7554:b5d2:d3e2',
    interfaces: [ { network: 'wedtest', ip: '10.249.2.2' } ],
    capacity: { cpu: 1, memory: 2048 },
    mounts: [
      {
        name: 'wedDisk',
        mountPoint: '/testdisk',
        size: 8589934592,
        state: 'ok',
        message: ''
      }
    ],
    env: {
      SSH_KEY: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC533B35CELELtgg2d7Tsi5KelLxR0FYUlrcTmRRQuTNP9arP01JYD8iHKqh6naMbbzR8+M0gdPEeRK4oVqQtEcH1C47vLyRI/4DqahAE2nTW08wtJM5uiIvcQ9H2HMzZ3MXYWWlgyHMgW2QXQxzrRS0NXvsY+4wxe97MMZs9MDs+d+X15DfG6JffjMHydi+4tHB50WmHe5tFscBFxLbgDBUxNGiwi3BQc1nWIuYwMMV1GFwT3ndyLAp19KPkEa/dffiqLdzkgs2qpXtfBhTZ/lFeQRc60DHCMWExr9ySDbavIMuBFylf/ZQeJXm9dFXJN7bBTbflZIIuUMjmrI7cU5eSuZqAj5l+Yb1mLN8ljmKSIM3/tkKbzXNH5AUtRVKTn+aEPvJAEYtserAxAP5pjy6nmegn0UerEE3DWEV2kqDig3aPSNhi9WSCykvG2tz7DIr0UP6qEIWYMC/5OisnSGj8w8dAjyxS9B0Jlx7DEmqPDNBqp8UcwV75Cot8vtIac= root@mohamed-Inspiron-3576'
    },
    entrypoint: '/sbin/zinit init',
    metadata: "{'testVMs': true}",
    description: 'test deploying VMs via ts grid3 client',
    corex: false
  }
]

```

**Comment by dmitri-alleo** [comment]
@mohamedamer453 yes thanks,
but only from the deployed VM I managed to set it up and deploy another VM,

if I use a Ubuntu 20.04 container from my local system or just try running it locally, then it throws an error
