### ISSUE TITLE
Failed to deploy gateway-fqdn-proxy

### ISSUE THREAD

**Issue by VenyaPanou** [threefoldtech/test_feedback#239]
**My data :** 
for ex it data for this case "Deploy Gateway with TLSPassthrough option"
![image](https://user-images.githubusercontent.com/106578096/173546958-c6bb1576-d6dd-4458-ba6c-d80333b590c7.png)

And run :  npx ts-node --project tsconfig-node.json scripts/fqdn_gateway.ts

Act.res : 
Error: Error: Failed to deploy gateway-fqdn-proxy with name john on node 1 due to: failed to setup fqdn proxy: failed to verify domain dns record: host doesn't point to the gateway ip
    at TwinDeploymentHandler.handle (/root/grid3_client_ts/src/high_level/twinDeploymentHandler.ts:393:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async GWModule.deploy_fqdn (/root/grid3_client_ts/src/modules/gateway.ts:42:27)
    at async GWModule.descriptor.value (/root/grid3_client_ts/src/modules/utils.ts:14:16)
    at async GWModule.descriptor.value (/root/grid3_client_ts/src/helpers/validator.ts:23:16)
    at async main (/root/grid3_client_ts/scripts/fqdn_gateway.ts:18:17)

Cases: TC203,TC204,TC202
Deploying on:
Testnet,
Grid v0.1.32

**Comment by ramezsaeed** [comment]
@VenyaPanou 
you need to use your own domain (you may create a new on on godady), so u can have access to it so you can connect.
You don't own the domain farming.threefold.io


https://library.threefold.me/info/manual/#/manual3_iac/grid3_javascript/manual__grid3_javascript_vm_gateways?id=detailed-explanation-1

![Screenshot from 2022-06-15 11-15-22](https://user-images.githubusercontent.com/16083592/173791142-937d2fa1-423f-4a49-84af-798cb17036b3.png)
