### ISSUE TITLE
The terraform-provider-grid_v1.6.1 plugin crashed!

### ISSUE THREAD

**Issue by fl0wm0ti0n** [threefoldtech/test_feedback#339]
I get this error with my grid_kubernetes deplyoment.

│ Error: Request cancelled
│ 
│   with module.kubernetes.grid_network.networks["network1"],
│   on ../../modules/threefold/main.tf line 31, in resource "grid_network" "networks":
│   31: resource "grid_network" "networks" {
│ 
│ The plugin.(*GRPCProvider).ValidateResourceConfig request was cancelled.
╵
╷
│ Error: Request cancelled
│ 
│   with module.kubernetes.grid_kubernetes.k8s1,
│   on ../../modules/threefold/main.tf line 41, in resource "grid_kubernetes" "k8s1":
│   41: resource "grid_kubernetes" "k8s1" {
│ 
│ The plugin.(*GRPCProvider).ApplyResourceChange request was cancelled.
╵

Stack trace from the terraform-provider-grid_v1.6.1 plugin:

panic: runtime error: index out of range [3] with length 0

goroutine 68 [running]:
github.com/threefoldtech/terraform-provider-grid/internal/provider.(*K8sDeployer).getK8sFreeIP(0xc00001c240, {{{0x0, 0x0, 0x0}, {0x0, 0x0, 0x0}}}, 0x1c870?)
        github.com/threefoldtech/terraform-provider-grid/internal/provider/resource_k8s.go:992 +0x1d4
github.com/threefoldtech/terraform-provider-grid/internal/provider.(*K8sDeployer).assignNodesIPs(0xc00001c240)
        github.com/threefoldtech/terraform-provider-grid/internal/provider/resource_k8s.go:520 +0xf7
github.com/threefoldtech/terraform-provider-grid/internal/provider.(*K8sDeployer).GenerateVersionlessDeployments(0xc00001c240, {0x43?, 0x0?})
        github.com/threefoldtech/terraform-provider-grid/internal/provider/resource_k8s.go:540 +0x36
github.com/threefoldtech/terraform-provider-grid/internal/provider.(*K8sDeployer).Deploy(0xc00001c240, {0xf58f60, 0xc000556600}, {0xf5d1b8, 0xc0000b6068}, 0xc0006e1ce0?, 0x10?)
        github.com/threefoldtech/terraform-provider-grid/internal/provider/resource_k8s.go:661 +0x75
github.com/threefoldtech/terraform-provider-grid/internal/provider.resourceK8sCreate({0xf58f60, 0xc000556600}, 0xcc9060?, {0xc56600?, 0xc00013d4a0})
        github.com/threefoldtech/terraform-provider-grid/internal/provider/resource_k8s.go:1011 +0x2d7
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc00023f6c0, {0xf58f98, 0xc000612240}, 0xd?, {0xc56600, 0xc00013d4a0})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.16.0/helper/schema/resource.go:707 +0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc00023f6c0, {0xf58f98, 0xc000612240}, 0xc00058e820, 0xc0000ecd80, {0xc56600, 0xc00013d4a0})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.16.0/helper/schema/resource.go:837 +0xa7a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc0003f0570, {0xf58ef0?, 0xc000107100?}, 0xc0002bd180)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.16.0/helper/schema/grpc_provider.go:1021 +0xe3c
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc000327040, {0xf58f98?, 0xc000593e30?}, 0xc000636700)
        github.com/hashicorp/terraform-plugin-go@v0.9.0/tfprotov5/tf5server/server.go:812 +0x515
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0xdc4d00?, 0xc000327040}, {0xf58f98, 0xc000593e30}, 0xc0002ee9c0, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.9.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0002228c0, {0xf5c478, 0xc00029e1a0}, 0xc0004f17a0, 0xc0003ef2f0, 0x14b2600, 0x0)
        google.golang.org/grpc@v1.45.0/server.go:1282 +0xccf
google.golang.org/grpc.(*Server).handleStream(0xc0002228c0, {0xf5c478, 0xc00029e1a0}, 0xc0004f17a0, 0x0)
        google.golang.org/grpc@v1.45.0/server.go:1619 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.45.0/server.go:921 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.45.0/server.go:919 +0x28a

Error: The terraform-provider-grid_v1.6.1 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

The files:
[terraform_k8s_deployment.zip](https://github.com/threefoldtech/test_feedback/files/10144270/terraform_k8s_deployment.zip)

**Comment by fl0wm0ti0n** [comment]
as i changed in the module/main.tf the network part it worked... i dotn know if the provider has a bug or if I'm the problem?

from:
# resource "grid_network" "networks" {
#   #for_each = local.networks
#   for_each = { for n in local.networks : n.name => n }
#     name                    = each.value.name
#     nodes                   = each.value.nodes
#     ip_range                = each.value.ip_range
#     description             = each.value.description
#     add_wg_access           = each.value.add_wg_access
# }

to:
resource "grid_network" "networks1" {

    name                    = local.networks[0].name
    nodes                   = local.networks[0].nodes
    ip_range                = local.networks[0].ip_range
    description             = local.networks[0].description
    add_wg_access           = local.networks[0].add_wg_access
}
